name: Behzad Tabibian
baseurl: "http://btabibian.github.io"
highlighter: pygments
fenced_code_blocks: true
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

